### ISSUE TITLE
support shortcuts in surround command

### ISSUE THREAD

**Issue by TeddyDD** [h-youhei/kakoune-surround#12]
some commands supports `q Q b g` shortcuts, It would be nice to add them to `surround` command as well

**Comment by h-youhei** [comment]
I thought it would be useful to surround with pressed char when I implemented `surround` command.
So I haven't supported `q Q b B a g` shortcuts intentionally.
But I have used the feature for symbols only.
I'll add `q Q b B a g` shortcuts for `surround` command.

**Comment by h-youhei** [comment]
for change surround

**Comment by TeddyDD** [comment]
Thanks :)
