### ISSUE TITLE
Undoing a surround leaves you with two cursors

### ISSUE THREAD

**Issue by evanrelf** [h-youhei/kakoune-surround#15]
After surrounding a selection, if you undo by pressing <kbd>u</kbd>, you are left with two cursors at the ends of the selection.

I don't know if this is expected behavior, but either way, I'd prefer it didn't do this. Is there anything like `undojoin` from Vim that could stop this from happening? I'd like to go back to one cursor or get my selection back when undoing.

**Comment by h-youhei** [comment]
mawww/kakoune#1184

I don't know how to workaround it on the plugin side.

**Comment by evanrelf** [comment]
I'll close the issue then
