### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by ejmr** [h-youhei/kakoune-surround#7]
The pop-up in the hidden command `_surrounding-object-info` has a small typo: `paranthes` should be `parentheses`.  It's such a small detail that I did not feel like going through the entire process of creating a pull-request, etc., so I simply wanted to mention the typo in an issue so that you can correct it the next time you're making a substantive change to the plugin.

**Comment by h-youhei** [comment]
Thank you, I'll fix it.
